baseURL = "https://example.com"
title = "MSC"
author = "MSC"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
#googleAnalytics = "UA-12345678-1"

# Disqus Comment System
#disqusShortname = ""

[params]

  mainSections = ['blog']

  googleFonts = true

  [params.logo]
    main = "img/logo/logo.svg"
    alt = "MSC Logo"

    # The size parameter is the class name of tailwindcss
    # https://tailwindcss.com/
    size = "h-14"

  [params.site]
    name = "MSC"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fontawesome = true

  [params.homepage_meta_tags]
    meta_description = "Homepage for the Michigan Snowboard Club at UofM"
    meta_og_title = "Michigan Snowboard Club"
    meta_og_type = "website"
    meta_og_url = "https://michigansnowboard.club"
    meta_og_image = "https://raw.githubusercontent.com/michigansnowboardclub/michigansnowboardclub.github.io/main/images/background.png"
    meta_og_description = "Homepage for the Michigan Snowboard Club at UofM"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "officers"
    name = "Officers"
    url = "/officers/"
    weight = 2

  [[menu.main]]
    identifier = "calendar"
    name = "Calendar"
    url = "/calendar/"
    weight = 3

  [[menu.main]]
    identifier = "merch"
    name = "Merch"
    url = "/merch/"
    weight = 4

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 5

  [[menu.main]]
    identifier = "dei"
    name = "DEI"
    url = "/dei/"
    weight = 6

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 7

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1
  
  [[menu.footer]]
    name = "Instagram"
    url = "https://www.instagram.com/mi_snowboard_club/?igshid=YmMyMTA2M2Y%3D"
      weight = 2

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/michigansnowboardclub/michigansnowboardclub.github.io"
    pre = "<i class='icon-github text-2xl'></i>"
      weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
